name: dl
dependencies:
  - numpy
  - pandas
  - matplotlib
  - ipykernel
  - pip
  - pip:
    - openai
    - graphviz
    - tensorflow==2.16.1
    - keras==2.15
    - tensorflow-probability==0.24.0
    - torch